version: '3.7'

services:
  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - './services/client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 8081:8080
    environment:
      - NODE_ENV=development
    
  web-api:
    build:
      context: ./services/web-api
      dockerfile: Dockerfile
    volumes:
      - './services/web-api:/usr/src/app'
    environment:
      - FLASK_ENV=development
    ports:
      - 5001:5000

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5435:5432
